local addon = SmartMark
addon.BuiltinMobDB = {
    ["17269"] = {
        name = "Bleeding Hollow Darkcaster",
        priorityType = "kill1",
        notes = "Dangerous caster. Interrupt.",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17270"] = {
        name = "Bleeding Hollow Archer",
        priorityType = "kill2",
        notes = "Ranged pressure. Pull with line of sight.",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17478"] = {
        name = "Bleeding Hollow Scryer",
        priorityType = "kill2",
        notes = "",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17517"] = {
        name = "Hellfire Sentry",
        priorityType = "kill2",
        notes = "Patrol or alarm mob. Pick up quickly.",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17271"] = {
        name = "Bonechewer Destroyer",
        priorityType = "kill3",
        notes = "",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17264"] = {
        name = "Bonechewer Ravener",
        priorityType = "kill3",
        notes = "Mobile threat. Keep it controlled.",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17281"] = {
        name = "Bonechewer Ripper",
        priorityType = "kill3",
        notes = "",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17455"] = {
        name = "Bonechewer Beastmaster",
        priorityType = "cc_sheep",
        notes = "Handler mob. Control pack early.",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17259"] = {
        name = "Bonechewer Hungerer",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17309"] = {
        name = "Hellfire Watcher",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17280"] = {
        name = "Shattered Hand Warhound",
        priorityType = "cc_trap",
        notes = "Mobile threat. Keep it controlled.",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17307"] = {
        name = "Vazruden the Herald",
        priorityType = "cc_trap",
        notes = "",
        zone = "Hellfire Ramparts",
        source = "builtin",
    },
    ["17395"] = {
        name = "Shadowmoon Summoner",
        priorityType = "kill1",
        notes = "Summons adds. Interrupt casts.",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17371"] = {
        name = "Shadowmoon Warlock",
        priorityType = "kill1",
        notes = "Dangerous caster. Interrupt.",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17397"] = {
        name = "Shadowmoon Adept",
        priorityType = "kill2",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17653"] = {
        name = "Shadowmoon Channeler",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17414"] = {
        name = "Shadowmoon Technician",
        priorityType = "kill2",
        notes = "Utility mob. Watch bombs or gadgets.",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17400"] = {
        name = "Felguard Annihilator",
        priorityType = "kill3",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17626"] = {
        name = "Laughing Skull Legionnaire",
        priorityType = "kill3",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17429"] = {
        name = "Fel Orc Neophyte",
        priorityType = "kill4",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17401"] = {
        name = "Felhound Manastalker",
        priorityType = "kill4",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17370"] = {
        name = "Laughing Skull Enforcer",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17491"] = {
        name = "Laughing Skull Rogue",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17624"] = {
        name = "Laughing Skull Warden",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17398"] = {
        name = "Nascent Fel Orc",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["18894"] = {
        name = "Felguard Brute",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17399"] = {
        name = "Seductress",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["19016"] = {
        name = "Hellfire Familiar",
        priorityType = "skip",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["17477"] = {
        name = "Hellfire Imp",
        priorityType = "skip",
        notes = "",
        zone = "The Blood Furnace",
        source = "builtin",
    },
    ["21126"] = {
        name = "Coilfang Scale-Healer",
        priorityType = "kill1",
        notes = "Healer. Interrupt major heals.",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17940"] = {
        name = "Coilfang Technician",
        priorityType = "kill2",
        notes = "Utility mob. Watch bombs or gadgets.",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17957"] = {
        name = "Coilfang Champion",
        priorityType = "kill3",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17959"] = {
        name = "Coilfang Slavehandler",
        priorityType = "kill4",
        notes = "Handler mob. Control pack early.",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17963"] = {
        name = "Wastewalker Slave",
        priorityType = "kill4",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17816"] = {
        name = "Bogstrok",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17962"] = {
        name = "Coilfang Collaborator",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17958"] = {
        name = "Coilfang Defender",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17961"] = {
        name = "Coilfang Enchantress",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17938"] = {
        name = "Coilfang Observer",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17960"] = {
        name = "Coilfang Soothsayer",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["21127"] = {
        name = "Coilfang Tempest",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17817"] = {
        name = "Greater Bogstrok",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17964"] = {
        name = "Wastewalker Worker",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["21128"] = {
        name = "Coilfang Ray",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["25740"] = {
        name = "Ahune",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["25756"] = {
        name = "Ahunite Coldwave",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["25757"] = {
        name = "Ahunite Frostwind",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["25755"] = {
        name = "Ahunite Hailstone",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["25865"] = {
        name = "Frozen Core",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Slave Pens",
        source = "builtin",
    },
    ["17730"] = {
        name = "Murkblood Healer",
        priorityType = "kill1",
        notes = "Healer. Interrupt major heals.",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17771"] = {
        name = "Murkblood Oracle",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17727"] = {
        name = "Wrathfin Sentry",
        priorityType = "kill2",
        notes = "Patrol or alarm mob. Pick up quickly.",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17723"] = {
        name = "Bog Giant",
        priorityType = "kill3",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["19632"] = {
        name = "Lykul Stinger",
        priorityType = "kill3",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17732"] = {
        name = "Lykul Wasp",
        priorityType = "kill3",
        notes = "Mobile threat. Keep it controlled.",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17734"] = {
        name = "Underbog Lord",
        priorityType = "kill3",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17990"] = {
        name = "Underbog Mushroom",
        priorityType = "kill3",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17729"] = {
        name = "Murkblood Spearman",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17728"] = {
        name = "Murkblood Tribesman",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17726"] = {
        name = "Wrathfin Myrmidon",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17735"] = {
        name = "Wrathfin Warrior",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17827"] = {
        name = "Claw",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17731"] = {
        name = "Fen Ray",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["22299"] = {
        name = "Spore Strider",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17724"] = {
        name = "Underbat",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["20465"] = {
        name = "Underbog Frenzy",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17725"] = {
        name = "Underbog Lurker",
        priorityType = "cc_banish",
        notes = "Mobile threat. Keep it controlled.",
        zone = "The Underbog",
        source = "builtin",
    },
    ["17871"] = {
        name = "Underbog Shambler",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Underbog",
        source = "builtin",
    },
    ["18331"] = {
        name = "Ethereal Darkcaster",
        priorityType = "kill1",
        notes = "Dangerous caster. Interrupt.",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18317"] = {
        name = "Ethereal Priest",
        priorityType = "kill1",
        notes = "Healer. Interrupt major heals.",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18313"] = {
        name = "Ethereal Sorcerer",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18312"] = {
        name = "Ethereal Spellbinder",
        priorityType = "kill2",
        notes = "Dangerous caster. Interrupt.",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18315"] = {
        name = "Ethereal Theurgist",
        priorityType = "kill2",
        notes = "Dangerous caster. Interrupt.",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18430"] = {
        name = "Ethereal Apprentice",
        priorityType = "kill4",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18309"] = {
        name = "Ethereal Scavenger",
        priorityType = "kill4",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18314"] = {
        name = "Nexus Stalker",
        priorityType = "kill4",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18311"] = {
        name = "Ethereal Crypt Raider",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["19306"] = {
        name = "Mana Leech",
        priorityType = "cc_trap",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18429"] = {
        name = "Arcane Fiend",
        priorityType = "cc_banish",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18394"] = {
        name = "Ethereal Wraith",
        priorityType = "cc_banish",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["19307"] = {
        name = "Nexus Terror",
        priorityType = "cc_banish",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18431"] = {
        name = "Ethereal Beacon",
        priorityType = "skip",
        notes = "",
        zone = "Mana-Tombs",
        source = "builtin",
    },
    ["18493"] = {
        name = "Auchenai Soulpriest",
        priorityType = "kill1",
        notes = "Healer. Interrupt major heals.",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18499"] = {
        name = "Unliving Sorcerer",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18495"] = {
        name = "Auchenai Vindicator",
        priorityType = "kill3",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18506"] = {
        name = "Raging Soul",
        priorityType = "kill3",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18501"] = {
        name = "Unliving Stalker",
        priorityType = "kill4",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18497"] = {
        name = "Auchenai Monk",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18702"] = {
        name = "Auchenai Necromancer",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18524"] = {
        name = "Angered Skeleton",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18478"] = {
        name = "Avatar of the Martyred",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18503"] = {
        name = "Phantasmal Possessor",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18521"] = {
        name = "Raging Skeleton",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18700"] = {
        name = "Reanimated Bones",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18441"] = {
        name = "Stolen Soul",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18500"] = {
        name = "Unliving Cleric",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18498"] = {
        name = "Unliving Soldier",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Auchenai Crypts",
        source = "builtin",
    },
    ["18934"] = {
        name = "Durnholde Mage",
        priorityType = "kill1",
        notes = "Dangerous caster. Interrupt or sheep.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["17833"] = {
        name = "Durnholde Warden",
        priorityType = "kill1",
        notes = "Heals, dispels, and fears. Hard stop target.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["18093"] = {
        name = "Tarren Mill Protector",
        priorityType = "kill1",
        notes = "Paladin healer. Sheep or kill immediately.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["17820"] = {
        name = "Durnholde Rifleman",
        priorityType = "kill2",
        notes = "Ranged pressure. Pull line of sight.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["17819"] = {
        name = "Durnholde Sentry",
        priorityType = "kill2",
        notes = "Patrol pull. Pick it up before extra aggro.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["18094"] = {
        name = "Tarren Mill Lookout",
        priorityType = "kill2",
        notes = "Escort-wave ranged support.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["17860"] = {
        name = "Durnholde Veteran",
        priorityType = "kill3",
        notes = "Standard melee.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["23175"] = {
        name = "Tarren Mill Guardsman",
        priorityType = "kill3",
        notes = "Standard escort trash.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["17840"] = {
        name = "Durnholde Tracking Hound",
        priorityType = "cc_trap",
        notes = "Beast control target.",
        zone = "Old Hillsbrad Foothills",
        source = "builtin",
    },
    ["18328"] = {
        name = "Sethekk Oracle",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18325"] = {
        name = "Sethekk Prophet",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18326"] = {
        name = "Sethekk Shaman",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18327"] = {
        name = "Time-Lost Controller",
        priorityType = "kill2",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18319"] = {
        name = "Time-Lost Scryer",
        priorityType = "kill2",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18320"] = {
        name = "Time-Lost Shadowmage",
        priorityType = "kill2",
        notes = "Dangerous caster. Interrupt.",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["21891"] = {
        name = "Avian Ripper",
        priorityType = "kill3",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18323"] = {
        name = "Sethekk Guard",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18318"] = {
        name = "Sethekk Initiate",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18322"] = {
        name = "Sethekk Ravenguard",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18321"] = {
        name = "Sethekk Talon Lord",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["19429"] = {
        name = "Avian Darkhawk",
        priorityType = "cc_trap",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["21904"] = {
        name = "Avian Warhawk",
        priorityType = "cc_trap",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["23132"] = {
        name = "Brood of Anzu",
        priorityType = "cc_trap",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["19428"] = {
        name = "Cobalt Serpent",
        priorityType = "cc_trap",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["18701"] = {
        name = "Dark Vortex",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["19205"] = {
        name = "Syth Arcane Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["19203"] = {
        name = "Syth Fire Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["19204"] = {
        name = "Syth Frost Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["19206"] = {
        name = "Syth Shadow Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sethekk Halls",
        source = "builtin",
    },
    ["17892"] = {
        name = "Infinite Chronomancer",
        priorityType = "kill2",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21136"] = {
        name = "Infinite Chronomancer",
        priorityType = "kill2",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["18994"] = {
        name = "Infinite Executioner",
        priorityType = "kill2",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21138"] = {
        name = "Infinite Executioner",
        priorityType = "kill2",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21698"] = {
        name = "Infinite Timereaver",
        priorityType = "kill3",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["17839"] = {
        name = "Rift Lord",
        priorityType = "kill3",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21140"] = {
        name = "Rift Lord",
        priorityType = "kill3",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["17952"] = {
        name = "Darkwater Crocolisk",
        priorityType = "kill4",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21818"] = {
        name = "Infinite Whelp",
        priorityType = "kill4",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["17023"] = {
        name = "Shadow Council Enforcer",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["18983"] = {
        name = "Blackfang Tarantula",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["17835"] = {
        name = "Infinite Assassin",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21137"] = {
        name = "Infinite Assassin",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21697"] = {
        name = "Infinite Chrono-Lord",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["18995"] = {
        name = "Infinite Vanquisher",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21139"] = {
        name = "Infinite Vanquisher",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21104"] = {
        name = "Rift Keeper",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["21148"] = {
        name = "Rift Keeper",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["18982"] = {
        name = "Sable Jaguar",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Black Morass",
        source = "builtin",
    },
    ["20990"] = {
        name = "Bloodwarder Physician",
        priorityType = "kill1",
        notes = "Healer. Interrupt major heals.",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19167"] = {
        name = "Bloodwarder Slayer",
        priorityType = "kill2",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19716"] = {
        name = "Mechanar Tinkerer",
        priorityType = "kill2",
        notes = "Utility mob. Watch bombs or gadgets.",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19168"] = {
        name = "Sunseeker Astromage",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["20988"] = {
        name = "Sunseeker Engineer",
        priorityType = "kill2",
        notes = "Utility mob. Watch bombs or gadgets.",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19231"] = {
        name = "Mechanar Crusher",
        priorityType = "kill3",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19713"] = {
        name = "Mechanar Wrecker",
        priorityType = "kill3",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19735"] = {
        name = "Tempest-Forge Destroyer",
        priorityType = "kill3",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19166"] = {
        name = "Tempest-Forge Patroller",
        priorityType = "kill3",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19510"] = {
        name = "Bloodwarder Centurion",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["20059"] = {
        name = "Sunseeker Netherbinder",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["20478"] = {
        name = "Arcane Servant",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["19712"] = {
        name = "Mechanar Driller",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["21062"] = {
        name = "Nether Wraith",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["20481"] = {
        name = "Raging Flames",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Mechanar",
        source = "builtin",
    },
    ["17694"] = {
        name = "Shadowmoon Darkcaster",
        priorityType = "kill1",
        notes = "Dangerous caster. Interrupt.",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["16594"] = {
        name = "Shadowmoon Acolyte",
        priorityType = "kill2",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17622"] = {
        name = "Sharpshooter Guard",
        priorityType = "kill2",
        notes = "Ranged pressure. Pull with line of sight.",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17427"] = {
        name = "Shattered Hand Archer",
        priorityType = "kill2",
        notes = "Ranged pressure. Pull with line of sight.",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17301"] = {
        name = "Shattered Hand Executioner",
        priorityType = "kill2",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["16507"] = {
        name = "Shattered Hand Sentry",
        priorityType = "kill2",
        notes = "Patrol or alarm mob. Pick up quickly.",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["16704"] = {
        name = "Shattered Hand Sharpshooter",
        priorityType = "kill2",
        notes = "Ranged pressure. Pull with line of sight.",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17356"] = {
        name = "Creeping Ooze",
        priorityType = "kill3",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17357"] = {
        name = "Creeping Oozeling",
        priorityType = "kill3",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17623"] = {
        name = "Reaver Guard",
        priorityType = "kill3",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17671"] = {
        name = "Shattered Hand Champion",
        priorityType = "kill3",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["16700"] = {
        name = "Shattered Hand Legionnaire",
        priorityType = "kill3",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["16699"] = {
        name = "Shattered Hand Reaver",
        priorityType = "kill3",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17578"] = {
        name = "Training Dummy",
        priorityType = "kill3",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17083"] = {
        name = "Fel Orc Convert",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17621"] = {
        name = "Heathen Guard",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17695"] = {
        name = "Shattered Hand Assassin",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17461"] = {
        name = "Shattered Hand Blood Guard",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["16593"] = {
        name = "Shattered Hand Brawler",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17465"] = {
        name = "Shattered Hand Centurion",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17464"] = {
        name = "Shattered Hand Gladiator",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17420"] = {
        name = "Shattered Hand Heathen",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17670"] = {
        name = "Shattered Hand Houndmaster",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["16523"] = {
        name = "Shattered Hand Savage",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17693"] = {
        name = "Shattered Hand Scout",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17462"] = {
        name = "Shattered Hand Zealot",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17669"] = {
        name = "Rabid Warhound",
        priorityType = "cc_trap",
        notes = "Mobile threat. Keep it controlled.",
        zone = "The Shattered Halls",
        source = "builtin",
    },
    ["17721"] = {
        name = "Coilfang Engineer",
        priorityType = "kill2",
        notes = "Utility mob. Watch bombs or gadgets.",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17803"] = {
        name = "Coilfang Oracle",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17722"] = {
        name = "Coilfang Sorceress",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17951"] = {
        name = "Steamrigger Mechanic",
        priorityType = "kill2",
        notes = "Utility mob. Watch bombs or gadgets.",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["21694"] = {
        name = "Bog Overlord",
        priorityType = "kill3",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17805"] = {
        name = "Coilfang Slavemaster",
        priorityType = "kill4",
        notes = "Handler mob. Control pack early.",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["21338"] = {
        name = "Coilfang Leper",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17800"] = {
        name = "Coilfang Myrmidon",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17801"] = {
        name = "Coilfang Siren",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17802"] = {
        name = "Coilfang Warrior",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["22891"] = {
        name = "Second Fragment Guardian",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["17917"] = {
        name = "Coilfang Water Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["21696"] = {
        name = "Steam Surger",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["21695"] = {
        name = "Tidal Surger",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Steamvault",
        source = "builtin",
    },
    ["18637"] = {
        name = "Cabal Shadow Priest",
        priorityType = "kill1",
        notes = "Healer. Interrupt major heals.",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18634"] = {
        name = "Cabal Summoner",
        priorityType = "kill1",
        notes = "Summons adds. Interrupt casts.",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18640"] = {
        name = "Cabal Warlock",
        priorityType = "kill1",
        notes = "Dangerous caster. Interrupt.",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18633"] = {
        name = "Cabal Acolyte",
        priorityType = "kill2",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18632"] = {
        name = "Cabal Executioner",
        priorityType = "kill2",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18639"] = {
        name = "Cabal Spellbinder",
        priorityType = "kill2",
        notes = "Dangerous caster. Interrupt.",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["19208"] = {
        name = "Summoned Cabal Acolyte",
        priorityType = "kill2",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18636"] = {
        name = "Cabal Assassin",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18631"] = {
        name = "Cabal Cultist",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18635"] = {
        name = "Cabal Deathsworn",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18830"] = {
        name = "Cabal Fanatic",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18794"] = {
        name = "Cabal Ritualist",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18638"] = {
        name = "Cabal Zealot",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["19209"] = {
        name = "Summoned Cabal Deathsworn",
        priorityType = "cc_sheep",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["22890"] = {
        name = "First Fragment Guardian",
        priorityType = "cc_trap",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18642"] = {
        name = "Fel Guardhound",
        priorityType = "cc_banish",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18796"] = {
        name = "Fel Overseer",
        priorityType = "cc_banish",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18663"] = {
        name = "Maiden of Discipline",
        priorityType = "cc_banish",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18848"] = {
        name = "Malicious Instructor",
        priorityType = "cc_banish",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["19226"] = {
        name = "Void Traveler",
        priorityType = "cc_banish",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18797"] = {
        name = "Tortured Skeleton",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["18641"] = {
        name = "Cabal Familiar",
        priorityType = "skip",
        notes = "",
        zone = "Shadow Labyrinth",
        source = "builtin",
    },
    ["17994"] = {
        name = "Bloodwarder Falconer",
        priorityType = "kill2",
        notes = "Ranged pressure. Pull with line of sight.",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19505"] = {
        name = "Sunseeker Channeler",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18420"] = {
        name = "Sunseeker Geomancer",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18421"] = {
        name = "Sunseeker Researcher",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18405"] = {
        name = "Tempest-Forge Peacekeeper",
        priorityType = "kill3",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18419"] = {
        name = "Bloodwarder Greenkeeper",
        priorityType = "kill4",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18404"] = {
        name = "Bloodwarder Steward",
        priorityType = "kill4",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19633"] = {
        name = "Bloodwarder Mender",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["17993"] = {
        name = "Bloodwarder Protector",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["20083"] = {
        name = "Summoned Bloodwarder Mender",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["20078"] = {
        name = "Summoned Bloodwarder Reservist",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18422"] = {
        name = "Sunseeker Botanist",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19486"] = {
        name = "Sunseeker Chemist",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19507"] = {
        name = "Sunseeker Gene-Splicer",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19509"] = {
        name = "Sunseeker Harvester",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19508"] = {
        name = "Sunseeker Herbalist",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18155"] = {
        name = "Bloodfalcon",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19513"] = {
        name = "Mutate Fear-Shrieker",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19598"] = {
        name = "Mutate Fleshlasher",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["25354"] = {
        name = "Mutate Fleshlasher",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19865"] = {
        name = "Mutate Horror",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19962"] = {
        name = "Blue Seedling",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["18587"] = {
        name = "Frayer",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19953"] = {
        name = "Frayer Protector",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19608"] = {
        name = "Frayer Wildling",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19557"] = {
        name = "Greater Frayer",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19969"] = {
        name = "Green Seedling",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19511"] = {
        name = "Nethervine Inciter",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19512"] = {
        name = "Nethervine Reaper",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19843"] = {
        name = "Nethervine Trickster",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19964"] = {
        name = "Red Seedling",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19949"] = {
        name = "Sapling",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19920"] = {
        name = "Thorn Flayer",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19919"] = {
        name = "Thorn Lasher",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["19958"] = {
        name = "White Seedling",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Botanica",
        source = "builtin",
    },
    ["20869"] = {
        name = "Arcatraz Sentinel",
        priorityType = "kill2",
        notes = "Patrol or alarm mob. Pick up quickly.",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20896"] = {
        name = "Ethereum Slayer",
        priorityType = "kill2",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20901"] = {
        name = "Sargeron Archer",
        priorityType = "kill2",
        notes = "Ranged pressure. Pull with line of sight.",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20882"] = {
        name = "Skulking Witch",
        priorityType = "kill2",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["21466"] = {
        name = "Harbinger Skyriss",
        priorityType = "kill3",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["21467"] = {
        name = "Harbinger Skyriss",
        priorityType = "kill3",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20865"] = {
        name = "Protean Horror",
        priorityType = "kill3",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20864"] = {
        name = "Protean Nightmare",
        priorityType = "kill3",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["21395"] = {
        name = "Protean Spawn",
        priorityType = "kill3",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["21346"] = {
        name = "Sightless Eye",
        priorityType = "kill3",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20866"] = {
        name = "Soul Devourer",
        priorityType = "kill3",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20857"] = {
        name = "Arcatraz Defender",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20859"] = {
        name = "Arcatraz Warder",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["21303"] = {
        name = "Defender Corpse",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["21702"] = {
        name = "Ethereum Life-Binder",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20897"] = {
        name = "Ethereum Wave-Caster",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20909"] = {
        name = "Sulfuron Magma-Thrower",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["21304"] = {
        name = "Warder Corpse",
        priorityType = "cc_sheep",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20911"] = {
        name = "Blackwing Drakonaar",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20906"] = {
        name = "Phase-Hunter",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["22892"] = {
        name = "Third Fragment Guardian",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20910"] = {
        name = "Twilight Drakonaar",
        priorityType = "cc_trap",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20908"] = {
        name = "Akkiris Lightning-Waker",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20905"] = {
        name = "Blazing Trickster",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20867"] = {
        name = "Death Watcher",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20868"] = {
        name = "Entropic Eye",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20880"] = {
        name = "Eredar Deathbringer",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20879"] = {
        name = "Eredar Soul-Eater",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20898"] = {
        name = "Gargantuan Abyssal",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20875"] = {
        name = "Negaton Screamer",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20873"] = {
        name = "Negaton Warp-Master",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20902"] = {
        name = "Sargeron Hellcaller",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20883"] = {
        name = "Spiteful Temptress",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20881"] = {
        name = "Unbound Devastator",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["20900"] = {
        name = "Unchained Doombringer",
        priorityType = "cc_banish",
        notes = "",
        zone = "The Arcatraz",
        source = "builtin",
    },
    ["24687"] = {
        name = "Sunblade Physician",
        priorityType = "kill1",
        notes = "Healer. Interrupt and kill fast.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24686"] = {
        name = "Sunblade Warlock",
        priorityType = "kill1",
        notes = "Dangerous caster. Interrupt shadow casts.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24696"] = {
        name = "Coilskar Witch",
        priorityType = "kill2",
        notes = "Caster pressure. Interrupt if possible.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24683"] = {
        name = "Sunblade Mage Guard",
        priorityType = "kill2",
        notes = "High caster pressure.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24685"] = {
        name = "Sunblade Magister",
        priorityType = "kill2",
        notes = "High caster pressure.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24777"] = {
        name = "Sunblade Sentinel",
        priorityType = "kill2",
        notes = "Heavy trash mob. Burns more rep than most.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24688"] = {
        name = "Wretched Skulker",
        priorityType = "kill2",
        notes = "Rogue-like opener threat.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24698"] = {
        name = "Ethereum Smuggler",
        priorityType = "kill3",
        notes = "Mixed ranged pressure.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24684"] = {
        name = "Sunblade Blood Knight",
        priorityType = "kill3",
        notes = "Standard melee.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24762"] = {
        name = "Sunblade Keeper",
        priorityType = "kill3",
        notes = "Standard melee.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24689"] = {
        name = "Wretched Bruiser",
        priorityType = "kill3",
        notes = "Standard melee.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24690"] = {
        name = "Wretched Husk",
        priorityType = "kill4",
        notes = "Low-priority wretched add.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24761"] = {
        name = "Brightscale Wyrm",
        priorityType = "cc_trap",
        notes = "Dragonkin CC target.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24697"] = {
        name = "Sister of Torment",
        priorityType = "cc_banish",
        notes = "Prime banish target.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
    ["24815"] = {
        name = "Sunblade Imp",
        priorityType = "skip",
        notes = "Low-health companion add.",
        zone = "Magisters' Terrace",
        source = "builtin",
    },
}
