local addon = SmartMark
addon.RaidMobDB = {
    -- =========================================================
    -- Karazhan
    -- =========================================================
    ["16504"] = {
        name = "Arcane Protector",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16485"] = {
        name = "Arcane Watchman",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17096"] = {
        name = "Astral Flare",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19781"] = {
        name = "Astral Flare",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19782"] = {
        name = "Astral Flare",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19783"] = {
        name = "Astral Flare",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17283"] = {
        name = "Astral Spark",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17248"] = {
        name = "Demon Chains",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16545"] = {
        name = "Ethereal Spellfilcher",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16544"] = {
        name = "Ethereal Thief",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16595"] = {
        name = "Fleshbeast",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16596"] = {
        name = "Greater Fleshbeast",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16540"] = {
        name = "Shadow Pillager",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["15550"] = {
        name = "Attumen the Huntsman",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19874"] = {
        name = "Baron Rafe Dreuger",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19875"] = {
        name = "Baroness Dorothea Millstipe",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16481"] = {
        name = "Ghastly Haunt",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16412"] = {
        name = "Ghostly Baker",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16470"] = {
        name = "Ghostly Philanthropist",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16414"] = {
        name = "Ghostly Steward",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19872"] = {
        name = "Lady Catriona Von'Indi",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17007"] = {
        name = "Lady Keira Berrybuck",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19873"] = {
        name = "Lord Crispin Ference",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["19876"] = {
        name = "Lord Robin Daris",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["184259"] = {
        name = "Night Lord",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16460"] = {
        name = "Night Mistress",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16406"] = {
        name = "Phantom Attendant",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16425"] = {
        name = "Phantom Guardsman",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16409"] = {
        name = "Phantom Guest",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17067"] = {
        name = "Phantom Hound",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16472"] = {
        name = "Phantom Stagehand",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16408"] = {
        name = "Phantom Valet",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17261"] = {
        name = "Restless Skeleton",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16471"] = {
        name = "Skeletal Usher",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16415"] = {
        name = "Skeletal Waiter",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16389"] = {
        name = "Spectral Apprentice",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["15547"] = {
        name = "Spectral Charger",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16411"] = {
        name = "Spectral Chef",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16468"] = {
        name = "Spectral Patron",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16473"] = {
        name = "Spectral Performer",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16410"] = {
        name = "Spectral Retainer",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16424"] = {
        name = "Spectral Sentry",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16407"] = {
        name = "Spectral Servant",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["15551"] = {
        name = "Spectral Stable Hand",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["15548"] = {
        name = "Spectral Stallion",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16482"] = {
        name = "Trapped Soul",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["184261"] = {
        name = "Wanton Host",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16459"] = {
        name = "Wanton Hostess",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16488"] = {
        name = "Arcane Anomaly",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16489"] = {
        name = "Chaotic Sentience",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17167"] = {
        name = "Conjured Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16177"] = {
        name = "Dreadbeast",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17267"] = {
        name = "Fiendish Imp",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16539"] = {
        name = "Homunculus",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["17229"] = {
        name = "Kil'rek",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16529"] = {
        name = "Magical Horror",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16530"] = {
        name = "Mana Warp",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16178"] = {
        name = "Phase Hound",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16176"] = {
        name = "Shadowbeast",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["184263"] = {
        name = "Zealous Consort",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16461"] = {
        name = "Zealous Paramour",
        priorityType = "cc_banish",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16170"] = {
        name = "Coldmist Stalker",
        priorityType = "cc_trap",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16171"] = {
        name = "Coldmist Widow",
        priorityType = "cc_trap",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16174"] = {
        name = "Greater Shadowbat",
        priorityType = "cc_trap",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16491"] = {
        name = "Mana Feeder",
        priorityType = "cc_trap",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16173"] = {
        name = "Shadowbat",
        priorityType = "cc_trap",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16492"] = {
        name = "Syphoner",
        priorityType = "cc_trap",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16175"] = {
        name = "Vampiric Shadowbat",
        priorityType = "cc_trap",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16526"] = {
        name = "Sorcerous Shade",
        priorityType = "skip",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    ["16525"] = {
        name = "Spell Shade",
        priorityType = "skip",
        notes = "",
        zone = "Karazhan",
        source = "builtin",
    },
    -- =========================================================
    -- Gruul's Lair
    -- =========================================================
    ["21350"] = {
        name = "Gronn-Priest",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Gruul's Lair",
        source = "builtin",
    },
    ["18834"] = {
        name = "Olm the Summoner",
        priorityType = "kill",
        killRank = 10,
        notes = "Summons adds. Kill fast.",
        zone = "Gruul's Lair",
        source = "builtin",
    },
    ["18836"] = {
        name = "Blindeye the Seer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Gruul's Lair",
        source = "builtin",
    },
    ["18835"] = {
        name = "Kiggler the Crazed",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Gruul's Lair",
        source = "builtin",
    },
    ["18832"] = {
        name = "Krosh Firehand",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Gruul's Lair",
        source = "builtin",
    },
    ["19389"] = {
        name = "Lair Brute",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Gruul's Lair",
        source = "builtin",
    },
    ["18847"] = {
        name = "Wild Fel Stalker",
        priorityType = "cc_banish",
        notes = "High-threat demon. Kill or banish.",
        zone = "Gruul's Lair",
        source = "builtin",
    },
    -- =========================================================
    -- Magtheridon's Lair
    -- =========================================================
    ["17256"] = {
        name = "Hellfire Channeler",
        priorityType = "kill",
        killRank = 10,
        notes = "Interrupt to prevent buffs or adds.",
        zone = "Magtheridon's Lair",
        source = "builtin",
    },
    ["18829"] = {
        name = "Hellfire Warder",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Magtheridon's Lair",
        source = "builtin",
    },
    ["17454"] = {
        name = "Burning Abyssal",
        priorityType = "cc_banish",
        notes = "",
        zone = "Magtheridon's Lair",
        source = "builtin",
    },
    -- =========================================================
    -- Serpentshrine Cavern
    -- =========================================================
    ["21220"] = {
        name = "Coilfang Priestess",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21806"] = {
        name = "Greyheart Spellbinder",
        priorityType = "kill",
        killRank = 20,
        notes = "Caster pressure. Interrupt when possible.",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21226"] = {
        name = "Tidewalker Shaman",
        priorityType = "kill",
        killRank = 20,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21865"] = {
        name = "Coilfang Ambusher",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21221"] = {
        name = "Coilfang Beast-Tamer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22055"] = {
        name = "Coilfang Elite",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21299"] = {
        name = "Coilfang Fathom-Witch",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21873"] = {
        name = "Coilfang Guardian",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21339"] = {
        name = "Coilfang Hate-Screamer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21298"] = {
        name = "Coilfang Serpentguard",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21301"] = {
        name = "Coilfang Shatterer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21964"] = {
        name = "Fathom-Guard Caribdis",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21966"] = {
        name = "Fathom-Guard Sharkkis",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21965"] = {
        name = "Fathom-Guard Tidalvess",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21230"] = {
        name = "Greyheart Nether-Mage",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21231"] = {
        name = "Greyheart Shield-Bearer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21232"] = {
        name = "Greyheart Skulker",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21263"] = {
        name = "Greyheart Technician",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21229"] = {
        name = "Greyheart Tidecaller",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22250"] = {
        name = "Rancid Mushroom",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21224"] = {
        name = "Tidewalker Depth-Seer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21227"] = {
        name = "Tidewalker Harpooner",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21228"] = {
        name = "Tidewalker Hydromancer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21920"] = {
        name = "Tidewalker Lurker",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21225"] = {
        name = "Tidewalker Warrior",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21251"] = {
        name = "Underbog Colossus",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21218"] = {
        name = "Vashj'ir Honor Guard",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22347"] = {
        name = "Colossus Lurker",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22352"] = {
        name = "Colossus Rager",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21958"] = {
        name = "Enchanted Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22119"] = {
        name = "Fathom Lurker",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21857"] = {
        name = "Inner Demon",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22035"] = {
        name = "Pure Spawn of Hydross",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21863"] = {
        name = "Serpentshrine Lurker",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22238"] = {
        name = "Serpentshrine Tidecaller",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21875"] = {
        name = "Shadow of Leotheras",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22009"] = {
        name = "Tainted Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22036"] = {
        name = "Tainted Spawn of Hydross",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21253"] = {
        name = "Tainted Water Elemental",
        priorityType = "cc_banish",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21508"] = {
        name = "Coilfang Frenzy",
        priorityType = "cc_trap",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22056"] = {
        name = "Coilfang Strider",
        priorityType = "cc_trap",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22120"] = {
        name = "Fathom Sporebat",
        priorityType = "cc_trap",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["21246"] = {
        name = "Serpentshrine Sporebat",
        priorityType = "cc_trap",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    ["22140"] = {
        name = "Toxic Sporebat",
        priorityType = "cc_trap",
        notes = "",
        zone = "Serpentshrine Cavern",
        source = "builtin",
    },
    -- =========================================================
    -- Tempest Keep
    -- =========================================================
    ["18806"] = {
        name = "Solarium Priest",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20033"] = {
        name = "Astromancer",
        priorityType = "kill",
        killRank = 20,
        notes = "Arcane caster. CC or kill before pull spreads.",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20046"] = {
        name = "Astromancer Lord",
        priorityType = "kill",
        killRank = 20,
        notes = "Arcane caster. CC or kill before pull spreads.",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20062"] = {
        name = "Grand Astromancer Capernian",
        priorityType = "kill",
        killRank = 20,
        notes = "Arcane caster. CC or kill before pull spreads.",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20044"] = {
        name = "Novice Astromancer",
        priorityType = "kill",
        killRank = 20,
        notes = "Arcane caster. CC or kill before pull spreads.",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20043"] = {
        name = "Apprentice Star Scryer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20031"] = {
        name = "Bloodwarder Legionnaire",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20035"] = {
        name = "Bloodwarder Marshal",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20036"] = {
        name = "Bloodwarder Squire",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20032"] = {
        name = "Bloodwarder Vindicator",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21270"] = {
        name = "Cosmic Infuser",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20047"] = {
        name = "Crimson Hand Battle Mage",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20049"] = {
        name = "Crimson Hand Blood Knight",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20048"] = {
        name = "Crimson Hand Centurion",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20050"] = {
        name = "Crimson Hand Inquisitor",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20040"] = {
        name = "Crystalcore Devastator",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20041"] = {
        name = "Crystalcore Sentinel",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21269"] = {
        name = "Devastation",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["19551"] = {
        name = "Ember of Al'ar",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21271"] = {
        name = "Infinity Blades",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20060"] = {
        name = "Lord Sanguinar",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20063"] = {
        name = "Master Engineer Telonicus",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20045"] = {
        name = "Nether Scryer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21268"] = {
        name = "Netherstrand Longbow",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21273"] = {
        name = "Phaseshift Bulwark",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21364"] = {
        name = "Phoenix Egg",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["18925"] = {
        name = "Solarium Agent",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21274"] = {
        name = "Staff of Disintegration",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20034"] = {
        name = "Star Scryer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20037"] = {
        name = "Tempest Falconer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20042"] = {
        name = "Tempest-Smith",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20064"] = {
        name = "Thaladred the Darkener",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21272"] = {
        name = "Warp Slicer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20052"] = {
        name = "Crystalcore Mechanic",
        priorityType = "cc_banish",
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["21362"] = {
        name = "Phoenix",
        priorityType = "cc_banish",
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20039"] = {
        name = "Phoenix-Hawk",
        priorityType = "cc_trap",
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    ["20038"] = {
        name = "Phoenix-Hawk Hatchling",
        priorityType = "cc_trap",
        notes = "",
        zone = "Tempest Keep",
        source = "builtin",
    },
    -- =========================================================
    -- Black Temple
    -- =========================================================
    ["23421"] = {
        name = "Ashtongue Channeler",
        priorityType = "kill",
        killRank = 10,
        notes = "Interrupt to prevent buffs or adds.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22964"] = {
        name = "Priestess of Delight",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22956"] = {
        name = "Priestess of Torment",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23215"] = {
        name = "Ashtongue Sorcerer",
        priorityType = "kill",
        killRank = 20,
        notes = "Caster pressure. Interrupt when possible.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23237"] = {
        name = "Bonechewer Blood Prophet",
        priorityType = "kill",
        killRank = 20,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23403"] = {
        name = "Illidari Assassin",
        priorityType = "kill",
        killRank = 20,
        notes = "Stealthed opener. Assign dedicated pickup.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23398"] = {
        name = "Angered Soul Fragment",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22959"] = {
        name = "Ardent Host",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22844"] = {
        name = "Ashtongue Battlelord",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23319"] = {
        name = "Ashtongue Broken",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23216"] = {
        name = "Ashtongue Defender",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23523"] = {
        name = "Ashtongue Elementalist",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22845"] = {
        name = "Ashtongue Mystic",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22847"] = {
        name = "Ashtongue Primalist",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23318"] = {
        name = "Ashtongue Rogue",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23524"] = {
        name = "Ashtongue Spiritbinder",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23374"] = {
        name = "Ashtongue Stalker",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22846"] = {
        name = "Ashtongue Stormcaller",
        priorityType = "kill",
        killRank = 30,
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22996"] = {
        name = "Blade of Azzinoth",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23196"] = {
        name = "Bonechewer Behemoth",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23235"] = {
        name = "Bonechewer Blade Fury",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23222"] = {
        name = "Bonechewer Brawler",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23239"] = {
        name = "Bonechewer Combatant",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23236"] = {
        name = "Bonechewer Shield Disciple",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23223"] = {
        name = "Bonechewer Spectator",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23028"] = {
        name = "Bonechewer Taskmaster",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22963"] = {
        name = "Bonechewer Worker",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22955"] = {
        name = "Charming Patron",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22873"] = {
        name = "Coilskar General",
        priorityType = "kill",
        killRank = 30,
        notes = "Naga trash. Watch fear/sleep auras.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22874"] = {
        name = "Coilskar Harpooner",
        priorityType = "kill",
        killRank = 30,
        notes = "Naga trash. Watch fear/sleep auras.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22875"] = {
        name = "Coilskar Sea-Caller",
        priorityType = "kill",
        killRank = 30,
        notes = "Naga trash. Watch fear/sleep auras.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22876"] = {
        name = "Coilskar Soothsayer",
        priorityType = "kill",
        killRank = 30,
        notes = "Naga trash. Watch fear/sleep auras.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22877"] = {
        name = "Coilskar Wrangler",
        priorityType = "kill",
        killRank = 30,
        notes = "Naga trash. Watch fear/sleep auras.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22965"] = {
        name = "Devoted Steward",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23030"] = {
        name = "Dragonmaw Sky Stalker",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23330"] = {
        name = "Dragonmaw Wind Reaver",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22960"] = {
        name = "Dragonmaw Wyrmcaller",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22929"] = {
        name = "Greater Shadowfiend",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23172"] = {
        name = "Hand of Gorefiend",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23400"] = {
        name = "Illidari Archon",
        priorityType = "kill",
        killRank = 30,
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23402"] = {
        name = "Illidari Battle-mage",
        priorityType = "kill",
        killRank = 30,
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23397"] = {
        name = "Illidari Blood Lord",
        priorityType = "kill",
        killRank = 30,
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23436"] = {
        name = "Image of Dementia",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23394"] = {
        name = "Promenade Sentinel",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22945"] = {
        name = "Shadowmoon Blood Mage",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22880"] = {
        name = "Shadowmoon Champion",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22882"] = {
        name = "Shadowmoon Deathshaper",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23147"] = {
        name = "Shadowmoon Grunt",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23018"] = {
        name = "Shadowmoon Houndmaster",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22879"] = {
        name = "Shadowmoon Reaver",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23047"] = {
        name = "Shadowmoon Soldier",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23049"] = {
        name = "Shadowmoon Weapon Master",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22939"] = {
        name = "Temple Acolyte",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23469"] = {
        name = "Enslaved Soul",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23389"] = {
        name = "Fallen Ally",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23401"] = {
        name = "Hungering Soul Fragment",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23371"] = {
        name = "Shadowmoon Fallen",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23111"] = {
        name = "Shadowy Construct",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23399"] = {
        name = "Suffering Soul Fragment",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22953"] = {
        name = "Wrathbone Flayer",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22878"] = {
        name = "Aqueous Lord",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22883"] = {
        name = "Aqueous Spawn",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22881"] = {
        name = "Aqueous Surger",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22997"] = {
        name = "Flame of Azzinoth",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22869"] = {
        name = "Illidari Boneslicer",
        priorityType = "cc_banish",
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23337"] = {
        name = "Illidari Centurion",
        priorityType = "cc_banish",
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22853"] = {
        name = "Illidari Defiler",
        priorityType = "cc_banish",
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22954"] = {
        name = "Illidari Fearbringer",
        priorityType = "cc_banish",
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23339"] = {
        name = "Illidari Heartseeker",
        priorityType = "cc_banish",
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22855"] = {
        name = "Illidari Nightlord",
        priorityType = "cc_banish",
        notes = "Illidari elite. High melee threat.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22957"] = {
        name = "Mistress of Dementia",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22962"] = {
        name = "Mistress of Woe",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23498"] = {
        name = "Parasitic Shadowfiend",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23375"] = {
        name = "Shadow Demon",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22848"] = {
        name = "Storm Fury",
        priorityType = "cc_banish",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22885"] = {
        name = "Dragon Turtle",
        priorityType = "cc_trap",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22884"] = {
        name = "Leviathan",
        priorityType = "cc_trap",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23232"] = {
        name = "Mutant War Hound",
        priorityType = "cc_trap",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23083"] = {
        name = "Shadowmoon Riding Hound",
        priorityType = "cc_trap",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22946"] = {
        name = "Shadowmoon War Hound",
        priorityType = "cc_trap",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    ["22849"] = {
        name = "Ashtongue Feral Spirit",
        priorityType = "skip",
        notes = "Broken mob. Mixed physical and caster roles.",
        zone = "Black Temple",
        source = "builtin",
    },
    ["23109"] = {
        name = "Vengeful Spirit",
        priorityType = "skip",
        notes = "",
        zone = "Black Temple",
        source = "builtin",
    },
    -- =========================================================
    -- Zul'Aman
    -- =========================================================
    ["24240"] = {
        name = "Alyson Antille",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23757"] = {
        name = "Amani Healing Ward",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23822"] = {
        name = "Amani Protective Ward",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23542"] = {
        name = "Amani'shi Axe Thrower",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24059"] = {
        name = "Amani'shi Beast Tamer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24374"] = {
        name = "Amani'shi Berserker",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23596"] = {
        name = "Amani'shi Flame Caster",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23597"] = {
        name = "Amani'shi Guardian",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24065"] = {
        name = "Amani'shi Handler",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23818"] = {
        name = "Amani'shi Hatcher",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24504"] = {
        name = "Amani'shi Hatcher",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24175"] = {
        name = "Amani'shi Lookout",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23581"] = {
        name = "Amani'shi Medicine Man",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24180"] = {
        name = "Amani'shi Protector",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23587"] = {
        name = "Amani'shi Reinforcement",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23889"] = {
        name = "Amani'shi Savage",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23586"] = {
        name = "Amani'shi Scout",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24549"] = {
        name = "Amani'shi Tempest",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23774"] = {
        name = "Amani'shi Trainer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23582"] = {
        name = "Amani'shi Tribesman",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23580"] = {
        name = "Amani'shi Warbringer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24225"] = {
        name = "Amani'shi Warrior",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24179"] = {
        name = "Amani'shi Wind Walker",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24243"] = {
        name = "Lord Raadan",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24241"] = {
        name = "Thurg",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24246"] = {
        name = "Darkheart",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24247"] = {
        name = "Koragg",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24245"] = {
        name = "Fenstalker",
        priorityType = "cc_banish",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24244"] = {
        name = "Gazakroth",
        priorityType = "cc_banish",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23584"] = {
        name = "Amani Bear",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24217"] = {
        name = "Amani Bear Mount",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23834"] = {
        name = "Amani Dragonhawk",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["23598"] = {
        name = "Amani Dragonhawk Hatchling",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24159"] = {
        name = "Amani Eagle",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24530"] = {
        name = "Amani Elder Lynx",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24043"] = {
        name = "Amani Lynx",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24064"] = {
        name = "Amani Lynx Cub",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24338"] = {
        name = "Amani Snake",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24242"] = {
        name = "Slither",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24858"] = {
        name = "Soaring Eagle",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24143"] = {
        name = "Spirit of the Lynx",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    ["24138"] = {
        name = "Tamed Amani Crocolisk",
        priorityType = "cc_trap",
        notes = "",
        zone = "Zul'Aman",
        source = "builtin",
    },
    -- =========================================================
    -- Sunwell Plateau
    -- =========================================================
    ["25509"] = {
        name = "Priestess of Torment",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25371"] = {
        name = "Sunblade Dawn Priest",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25370"] = {
        name = "Sunblade Dusk Priest",
        priorityType = "kill",
        killRank = 10,
        notes = "Healer. Kill or interrupt immediately.",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25484"] = {
        name = "Shadowsword Assassin",
        priorityType = "kill",
        killRank = 20,
        notes = "Stealthed opener. Assign dedicated pickup.",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25744"] = {
        name = "Dark Fiend",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25588"] = {
        name = "Hand of the Deceiver",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25798"] = {
        name = "Shadowsword Berserker",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25837"] = {
        name = "Shadowsword Commander",
        priorityType = "kill",
        killRank = 30,
        notes = "Leader mob. Auras or patrol buffs. Kill fast.",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25485"] = {
        name = "Shadowsword Deathbringer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25799"] = {
        name = "Shadowsword Fury Mage",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25508"] = {
        name = "Shadowsword Guardian",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25506"] = {
        name = "Shadowsword Lifeshaper",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25483"] = {
        name = "Shadowsword Manafiend",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25373"] = {
        name = "Shadowsword Soulbinder",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25486"] = {
        name = "Shadowsword Vanquisher",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25502"] = {
        name = "Shield Orb",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25708"] = {
        name = "Sinister Reflection",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25367"] = {
        name = "Sunblade Arch Mage",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25363"] = {
        name = "Sunblade Cabalist",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25507"] = {
        name = "Sunblade Protector",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25372"] = {
        name = "Sunblade Scout",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25368"] = {
        name = "Sunblade Slayer",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25369"] = {
        name = "Sunblade Vindicator",
        priorityType = "kill",
        killRank = 30,
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25268"] = {
        name = "Unyielding Dead",
        priorityType = "cc_shackle",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25593"] = {
        name = "Apocalypse Guard",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25599"] = {
        name = "Cataclysm Hound",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25595"] = {
        name = "Chaos Gazer",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25592"] = {
        name = "Doomfire Destroyer",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25948"] = {
        name = "Doomfire Shard",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["26101"] = {
        name = "Fire Fiend",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25597"] = {
        name = "Oblivion Mage",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25591"] = {
        name = "Painbringer",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["24892"] = {
        name = "Sathrovarr the Corruptor",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25772"] = {
        name = "Void Sentinel",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25824"] = {
        name = "Void Spawn",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25598"] = {
        name = "Volatile Felfire Fiend",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25851"] = {
        name = "Volatile Fiend",
        priorityType = "cc_banish",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
    ["25867"] = {
        name = "Sunblade Dragonhawk",
        priorityType = "cc_trap",
        notes = "",
        zone = "Sunwell Plateau",
        source = "builtin",
    },
}
